### ISSUE TITLE
lambda.invoke fails on Microsoft Edge

### ISSUE THREAD

**Issue by djabry** [aws/aws-sdk-js#1075]
All Lambda invocations fail on Microsoft Edge with a network error.

I'm not sure whether this is a bug with Edge or something that needs to be fixed in the AWS SDK.

This is a simple example that fails on Edge: http://codepen.io/djabry/pen/EyRmrZ

**Comment by lukevanhorn** [comment]
I'm getting this same error in IE 11 on Win8.

**Comment by LiuJoyceC** [comment]
Hi @djabry and @lukevanhorn 

Thanks for opening this issue. This is a known bug with IE11 and Edge. IE11 and Edge browsers do not always correctly expose headers specified by the server. We have run into this issue recently with other services, and it doesn't seem to affect any browsers other than IE and Edge. I also found a Stack Overflow question regarding this (although it only mentions IE11): http://stackoverflow.com/questions/34696157/ie-misses-headers-angular-http

I would suggest opening a ticket with Microsoft about this. As this is not an issue with the SDK or with AWS, I will be closing this issue. Thanks!

**Comment by LiuJoyceC** [comment]
Hi @djabry and @lukevanhorn 

Lambda has deployed a fix, and it should now work in IE and Edge. Thanks!

**Comment by lukevanhorn** [comment]
Hi @LiuJoyceC,

Thanks so much for the follow-up.  That's great to hear.  Unfortunately, I'm still experiencing the same issue when I tested my site just now, is there a version of the SDK we should be using or is this a change to the Lambda service pre-flight response that somehow works around the IE bug?  

Fyi, I submitted a bug to the IE team:  https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8433404

Thanks,
Luke

**Comment by djabry** [comment]
Many thanks for the fix @LiuJoyceC! It now works for me.

Daniel

**Comment by LiuJoyceC** [comment]
Hi @lukevanhorn 

I spoke with the Lambda team and they have not yet deployed the fix to all regions. What region are you making your lambda calls to? I will follow up with the service team and let you know when it has been deployed to your region. And thanks for opening the issue with IE!

@djabry, glad to hear it works for you!

**Comment by lukevanhorn** [comment]
Hi @LiuJoyceC ,

I'm using us-east-1.  @djabry was kind enough to help test my application and confirmed that the update hasn't been deployed to my region yet.  I'll keep an eye out for your update.

Thanks!
Luke

**Comment by mojojr** [comment]
Has the fix been deployed to us-east-1 yet?  Seeing the same issues 

Thanks
Brendan

**Comment by chrisradek** [comment]
Hey @mojojr 
Lambda has deployed the change to some but not all regions yet. We'll update this issue once they change has been deployed to more regions.

**Comment by lukevanhorn** [comment]
Hi @mojojr, 

As of yesterday, IE 11/Edge is working for me in **us-east-1**.  Big thanks to the Lambda team!

Luke

**Comment by mojojr** [comment]
Yep, I can confirm.  

Thanks!

**Comment by LiuJoyceC** [comment]
I've confirmed it, too. Glad it's working!
