### ISSUE TITLE
Compilation errors with v2.7.3

### ISSUE THREAD

**Issue by phubbard** [aws/aws-sdk-js#1229]
With both 6.6.0 and 7.0.0 versions of node, I get this when compiling a TypeScript/Nodejs project:

node_modules/aws-sdk/clients/acm.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.

Workaround is to delete node_modules/aws-sdk/clients/*.d.ts 
but I can't do that on our CI box.

**Comment by chrisradek** [comment]
@phubbard 
Are you currently pulling in typings for the node environment? Can you install @types/node as a dependency?

#1228 Will remove the need to install the node typings, but you'll still get errors in some cases if the typescript compiler can't resolve some global imports (like http, streams, other native node modules).

**Comment by phubbard** [comment]
Apologies, but I'm new to TS and have inherited this codebase. How do I answer your question? Do you mean 'is node in the package.json'?

Additional info: Pinning the aws-sdk version to 2.6.15 fixes the compile error, so I have a workaround.

**Comment by chrisradek** [comment]
You can specify a dependency in your package.json file on the `@types/node` package. This will provide type definitions for the native node modules that the SDK can then reference. The reason this isn't included as a dependency of the SDK is to avoid type definition conflicts for projects that are already pulling in node typings, and to allow you to specify the version that matches your node environment.

**Comment by phubbard** [comment]
That leads to a different error:
node_modules/@types/node/index.d.ts(70,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'main' must be of type 'any', but here has type 'NodeModule'.
[14:42:36] gulp-notify: [Gulp] Typescript compiler error

**Comment by chrisradek** [comment]
What version of TypeScript are you using?

**Comment by phubbard** [comment]
2.0.6

**Comment by chrisradek** [comment]
Hmm, do you have any other type definitions defined in your project? It seems like something defined in @types/node is defined in another project. If you can share any types you're using, I can create a test case to make sure #1228 fixes your issue as well.

**Comment by phubbard** [comment]
Sure, happy to. Again, I'm a newbie, so which files would help?

**Comment by chrisradek** [comment]
@phubbard 
Sorry for the delay. Can you actually see if the latest version of the SDK helps? I've merged #1228 which removes the explicit dependency on `@types/node`, though you still need to have the node native modules typings defined somewhere.

If the latest version doesn't work, can you share your `tsconfig.json` file, and any other files that describe which typings you may be pulling into your project?

**Comment by phubbard** [comment]
Still broken - the typings directory has aws-sdk, bluebird, connect, cors, crypto-js, express-serve-static-core, form-data, lodash, mime, modules, moment, mustache, node, nodemailer, nodemailer-direct-transport, nodemailer-ses-transport, nodemailer-smtp-transport, redis, request, serve-static, uuid, validator, winston and ws

**Comment by chrisradek** [comment]
Can you share what error you're getting now, or is it the same as before?

**Comment by phubbard** [comment]
node_modules/aws-sdk/lib/config.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
[09:02:46] gulp-notify: [Gulp] Typescript compiler error

**Comment by chrisradek** [comment]
Ah I see, I missed a reference to node. I'll double-check all the definition files and update again.

Thanks for your help so far @phubbard!

**Comment by Roam-Cooper** [comment]
The problem is that the typings tool only strips references in the typings that it installs whereas there's no way to strip references in a declaration file in a node module afaik. Putting a declaration file in your node module is not a smart move.

References to node in other declarations installed by typings get stripped and replaced with a reference to the common node declaration index.d.ts file. Having a .d.ts in your project breaks this.

**Comment by chrisradek** [comment]
@phubbard 
I went through and removed all references to `/// <reference types="node" />`. I also updated the typings to better match patterns some 3rd party typings used.

Can you attempt using the latest version of the SDK again? If it still doesn't work, can you share your typings.json file?

**Comment by phubbard** [comment]
That fixed it - thank you!

**Comment by chrisradek** [comment]
Excellent! Thanks for your patience with this, closing!
